name       : python-cairo
version    : 1.18.0
release    : 8
source     :
    - https://github.com/pygobject/pycairo/releases/download/v1.18.0/pycairo-1.18.0.tar.gz : abd42a4c9c2069febb4c38fe74bfc4b4a9d3a89fea3bc2e4ba7baff7a20f783f
homepage   : https://cairographics.org/
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python Cairo Bindings
description: |
    Python Cairo Bindings
builddeps  :
    - pkgconfig(cairo)
    - python-pytest
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    %python_test
