name       : python-cairo
version    : 1.14.1
release    : 7
source     :
    - https://github.com/pygobject/pycairo/releases/download/v1.14.1/pycairo-1.14.1.tar.gz : 0d13a0a6eeaf0c357db04392943eb9b25767445608d31dde1307f003f68c5754
homepage   : http://cairographics.org/
license    : GPL-2.0
component  : programming.python
summary    : Python Cairo Bindings
description: |
    Python Cairo Bindings
builddeps  :
    - pkgconfig(cairo-gobject)
build      : |
    %python_setup
install    : |
    %python_install
