name       : python-cairo
version    : 1.18.2
release    : 10
source     :
    - https://github.com/pygobject/pycairo/releases/download/v1.18.2/pycairo-1.18.2.tar.gz : dcb853fd020729516e8828ad364084e752327d4cff8505d20b13504b32b16531
homepage   : https://cairographics.org/
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python Cairo Bindings
description: |
    Python Cairo Bindings
builddeps  :
    - pkgconfig(cairo)
    - python2-pytest
build      : |
    %python_setup
install    : |
    %python_install
check      : |
    %python_test
